version: '{branch}-{build}'

image:
- Visual Studio 2017

platform:
- x64

configuration:
- Release

build:
  parallel: true
  verbosity: minimal

matrix:
  fast_finish: true

environment:
  matrix:
  - PYTHON: "C:\\Python36-x64"

install:
- git submodule update --init --recursive
- SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
- pip install -r requirements.txt

before_build:
- if "%PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- mkdir build
- cd build
- if "%PLATFORM%"=="x64" set GENERATOR="Visual Studio 15 2017 Win64"
- cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G%GENERATOR% -DSTK_BUILD_TESTS=1 -DSTK_WARNINGS_ARE_ERRORS=1 -DDF_BUILD_PYTHON_WRAPPER=ON

build_script:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmake --build . --config %CONFIGURATION%
- cd ..
- python setup.py install -DCMAKE_GENERATOR_PLATFORM=%PLATFORM%

test_script:
- ctest --output-on-failure
- python -m unittest discover test